# Generated by Django 5.2.17 on 2026-08-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['latitude', 'longitude'], name='api_fuelsta_latitud_a8079e_idx'),
        ),
    ]
